const data = [
  {
    id: 0,
    name: 'string',
    assembly_term: 22,
    profile_url: 'string',
    political_party: '정의당',
    elected_count: 2,
    total_promise_count: 78,
    completed_promise_count: 40,
    in_progress_promise_count: 30,
    pending_promise_count: 7,
    discarded_promise_count: 1,
    other_promise_count: 0,
    resolve_required_promise_count: 432,
    resolved_promise_count: 123,
    total_required_funds: 0,
    total_secured_funds: 0,
    total_executed_funds: 0,
    promise_count_detail: {
      completed_national_promise_count: 10,
      total_national_promise_count: 9,
      completed_local_promise_count: 8,
      total_local_promise_count: 7,
      completed_legislative_promise_count: 6,
      total_legislative_promise_count: 5,
      completed_financial_promise_count: 4,
      total_financial_promise_count: 3,
      completed_in_term_promise_count: 2,
      total_in_term_promise_count: 23,
      completed_after_term_promise_count: 45,
      total_after_term_promise_count: 67,
      completed_ongoing_business_promise_count: 98,
      total_ongoing_business_promise_count: 28,
      completed_new_business_promise_count: 45,
      total_new_business_promise_count: 13,
    },
    committee: [
      {
        id: 0,
        is_main: true,
        name: 'string',
      },
    ],
    constituency: [
      {
        id: 0,
        region: 'string',
        district: 'string',
        section: 'string',
      },
    ],
  },
  {
    id: 1,
    name: 'string',
    assembly_term: 22,
    profile_url: 'string',
    political_party: '어쩌구당',
    elected_count: 2,
    total_promise_count: 78,
    completed_promise_count: 40,
    in_progress_promise_count: 30,
    pending_promise_count: 7,
    discarded_promise_count: 1,
    other_promise_count: 0,
    resolve_required_promise_count: 0,
    resolved_promise_count: 0,
    total_required_funds: 3000,
    total_secured_funds: 2000,
    total_executed_funds: 10000,
    promise_count_detail: {
      completed_national_promise_count: 10,
      total_national_promise_count: 9,
      completed_local_promise_count: 8,
      total_local_promise_count: 7,
      completed_legislative_promise_count: 6,
      total_legislative_promise_count: 5,
      completed_financial_promise_count: 4,
      total_financial_promise_count: 3,
      completed_in_term_promise_count: 2,
      total_in_term_promise_count: 23,
      completed_after_term_promise_count: 45,
      total_after_term_promise_count: 67,
      completed_ongoing_business_promise_count: 98,
      total_ongoing_business_promise_count: 28,
      completed_new_business_promise_count: 45,
      total_new_business_promise_count: 13,
    },
    committee: [
      {
        id: 0,
        is_main: true,
        name: 'string',
      },
    ],
    constituency: [
      {
        id: 0,
        region: 'string',
        district: 'string',
        section: 'string',
      },
    ],
  },
];
